name: Gource Action
on:
  repository_dispatch:
    types: [activity_push]
  workflow_dispatch: {}

jobs:       
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Gen index.html
        run: |
          mkdir gource
          cat > ./gource/index.html <<EOL
            <meta http-equiv="refresh" content="0; url=gource.mp4" />
            <title>Gource V2B-5</title>
            <b><a href="gource.mp4">video</a></b>
          EOL
      - name: Gource-Action
        uses: NBprojekt/gource-action@v1.0.1
        with:
          gource_title: 'V2B-5'
          gource_dir_depth: 5
          gource_seconds_per_day: 3
          gource_resolution: '1440p'
      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.githubKey }}
          BRANCH: gh-pages
          FOLDER: gource
          CLEAN: true
          SINGLE_COMMIT: true
