# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: postman + Java CI with Maven

on: deployment_status

jobs:
  postman:
    if: github.event.deployment_status.state == "success"
    runs-on: ubuntu-latest

    steps:
    - name: Run API Tests
      uses: anthonyvscode/newman-action@v1
      with:
        collection: bep2-project.postman_collection.json
        reporters: cli