# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: postman

on: deployment_status

jobs:
  postman:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Run API Tests
      uses: anthonyvscode/newman-action@v1
      with:
        apiKey: ${{ secrets.postmanApiKey }}
        collection: 229781-3aba0364-e806-49b3-93b4-ba9c1877aedd
        reporters: cli
        folder: done

    - name: Output summary to console
      run: echo ${{ steps.run-api-tests.outputs.summary }}
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run API Tests
      uses: anthonyvscode/newman-action@v1
      with:
        collection: postman-tests/collection1.postman_collection.json
        reporters: cli

    - name: Output summary to console
      run: echo ${{ steps.run-api-tests.outputs.summary }}
